apiVersion: apps/v1
kind: Deployment
metadata:
  name: firsthello-deployment
  labels:
    app: firsthello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firsthello
  template:
    metadata:
      labels:
        app: firsthello
    spec:
      containers:
      - name: firsthello
        image: akiladoc/node-web-app
        ports:
        - containerPort: 8080